### ISSUE TITLE
Create data models for users/messages

### ISSUE THREAD

**Issue by corimstyle** [otakaran/mustang-messenger#15]
We need data models for users and messages in the back end.

**Comment by otakaran** [comment]
this issue is solved with firebase api

**Comment by otakaran** [comment]
Still no done

**Comment by otakaran** [comment]
I will be working on this today using Cloud Firestore

Time estimate: 1 hour

**Comment by otakaran** [comment]
Complete on db side. Time spent was 30 minutes.
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/9439760/109057549-bcd24180-7696-11eb-8571-190ec170eda6.png">
