### ISSUE TITLE
Generating and assigning unique user ID codes

### ISSUE THREAD

**Issue by ethanchoi1** [otakaran/mustang-messenger#9]
As a user, I would like to be able to find and message people based on some form of user identification, such as a unique user ID code.

**Comment by otakaran** [comment]
It appears that this can be handled in Firebase, I recommend resolving this issue to prioritize other tasks.
<img width="984" alt="image" src="https://user-images.githubusercontent.com/9439760/107997015-ad683f80-6f96-11eb-9d36-7838444cef95.png">
